# Generated by Django 4.0 on 2023-12-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonquest_django', '0004_remove_user_email_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campusID', models.AutoField(primary_key=True, serialize=False)),
                ('campusName', models.CharField(max_length=255)),
                ('campusInfo', models.TextField()),
            ],
        ),
    ]
