# Generated by Django 4.0 on 2023-12-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonquest_django', '0005_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='cq_Campus',
            fields=[
                ('campusID', models.AutoField(primary_key=True, serialize=False)),
                ('campusName', models.CharField(max_length=255)),
                ('campusInfo', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
