# Generated by Django 4.0 on 2023-12-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonquest_django', '0007_campus_delete_cq_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='locationCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=255)),
            ],
        ),
    ]
