# Generated by Django 4.0 on 2023-12-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonquest_django', '0008_locationcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('collegeID', models.AutoField(primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=255)),
                ('collegeMap', models.CharField(max_length=255)),
                ('collegePic1', models.CharField(max_length=255)),
                ('collegePic2', models.CharField(max_length=255)),
                ('collegePic3', models.CharField(max_length=255)),
                ('collegeInfo', models.TextField()),
                ('campusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimsonquest_django.campus')),
            ],
        ),
    ]
