# Generated by Django 4.0 on 2023-12-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonquest_django', '0010_alter_college_collegemap_alter_college_collegepic1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facilityID', models.AutoField(primary_key=True, serialize=False)),
                ('facilityName', models.CharField(max_length=255)),
                ('facilityMap', models.ImageField(blank=True, null=True, upload_to='facility_images/')),
                ('facilityPic1', models.ImageField(blank=True, null=True, upload_to='facility_images/')),
                ('facilityPic2', models.ImageField(blank=True, null=True, upload_to='facility_images/')),
                ('facilityPic3', models.ImageField(blank=True, null=True, upload_to='facility_images/')),
                ('facilityInfo', models.TextField()),
                ('campusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimsonquest_django.campus')),
            ],
        ),
    ]
