# Generated by Django 4.0 on 2023-12-05 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonquest_django', '0012_user_email_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highschool',
            fields=[
                ('hsID', models.AutoField(primary_key=True, serialize=False)),
                ('hsName', models.CharField(max_length=255)),
                ('hsMap', models.ImageField(blank=True, null=True, upload_to='highschool_images/')),
                ('hsPic1', models.ImageField(blank=True, null=True, upload_to='highschool_images/')),
                ('hsPic2', models.ImageField(blank=True, null=True, upload_to='highschool_images/')),
                ('hsPic3', models.ImageField(blank=True, null=True, upload_to='highschool_images/')),
                ('hsInfo', models.TextField()),
                ('campusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimsonquest_django.campus')),
            ],
        ),
    ]
