# Generated by Django 4.0 on 2023-12-05 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonquest_django', '0013_highschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementary',
            fields=[
                ('elemID', models.AutoField(primary_key=True, serialize=False)),
                ('elemName', models.CharField(max_length=255)),
                ('elemMap', models.ImageField(blank=True, null=True, upload_to='highschool_images/')),
                ('elemPic1', models.ImageField(blank=True, null=True, upload_to='highschool_images/')),
                ('elemPic2', models.ImageField(blank=True, null=True, upload_to='highschool_images/')),
                ('elemPic3', models.ImageField(blank=True, null=True, upload_to='highschool_images/')),
                ('elemInfo', models.TextField()),
                ('campusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimsonquest_django.campus')),
            ],
        ),
    ]
