# Generated by Django 4.0 on 2023-12-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonquest_django', '0015_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
