# Generated by Django 4.0 on 2023-12-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonquest_django', '0016_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
    ]
