# Generated by Django 4.0 on 2023-12-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonquest_django', '0017_remove_user_firstname_remove_user_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullName',
            new_name='full_name',
        ),
    ]
