# Generated by Django 4.0 on 2023-12-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonquest_django', '0018_rename_fullname_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='fullName',
        ),
    ]
